### ISSUE TITLE
invalid response / Cmd Response (05)

### ISSUE THREAD

**Issue by TobiasHuber1980** [mlnoga/rct#10]
siehe [evcc #9146](https://github.com/evcc-io/evcc/issues/9146)

folgende Fehlermeldungen:

`battery 1 soc: invalid response: Cmd Response (05) Id #INVALID (4BC0F974) Data [70 60 232 0]`

`battery 1 soc: invalid response: Cmd Response (05) Id #INVALID (C0A7074F) Data [58 189 129 108 80 83 32 49 48 46 48 32 86 87 52 81 0 0 0 0 0 0 0 0 0 0 0 0 50 51 42 69 79 14 25 195 35 158 21 63 0 0 7 13 0 0 0 0 50 46 51 46 53 54 54 49 0 0 0 0 0 0 0 0 48 48 54 53 66 52 48 50 51 57 49 55 0 0 0 0 0 0 0 0 223 21 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]`

`grid energy: invalid response: Cmd Response (05) Id #INVALID (C0A7074F) Data [71 240 52 38 80 83 32 56 46 48 32 68 83 76 69 0 0 0 0 0 0 0 0 0 0 0 0 0 119 61 110 69 200 249 61 193 0 0 0 63 0 0 5 13 0 0 0 0 50 46 51 46 53 54 54 49 0 0 0 0 0 0 0 0 48 48 54 53 66 52 56 50 51 50 52 54 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]`

**Comment by hrncvk** [comment]
Hi. Verstehe ich richtig, dass das ein RCT issue ist? Hat mich interessiert ob ich alleine bin mit dem Problem oder ob es auch andere haben...

**Comment by mlnoga** [comment]
Danke, ich schaue es mir an.

**Comment by mlnoga** [comment]
Erster Zwischenstand: evcc fragt den Ladezustand der Batterie ab (batterySoC, ID 0x959930BF). Vom RCT Laderegler kommt zwar ein Datenpaket mit gültiger Checksumme zurück. Doch es enthält einen ganz anderen Datenpunkt, nämlich die Spitzenleistung der Solarzellen. Hier der entsprechende Auszug aus der Herstellerdokumentation:

```
0x4BC0F974, // 255: buf_v_control.power_reduction_max_solar | t_float |
Solar plant peak power [Wp]
```

evcc fragt wieder den Ladezustand ab. Der RCT Laderegler gibt stattdessen folgenden Wert zurück:
```
0xC0A7074F, // 681: net.slave_data | t_string |
net.slave_data
```

Und das gleiche erneut bei Abfrage der Netzenergie (0xA59C8428).

Wie gehen wir robust damit um, wenn das Gerät nicht abgefragte Werte zurückliefert? Ein möglicher Weg könnte sein, die Abfrage einfach erneut zu versuchen. Dafür könnte man in https://github.com/mlnoga/rct/blob/main/connection.go#L108 einen Retry einbauen. Oder man ändert die bisher synchrone Architektur, und lagert das Auslesen von Antworten in einen nebenläufigen Thread aus. Das wäre ggf. robuster, aber auch deutlich aufwändiger.

Wie schwerwiegend sind denn die aktuellen Auswirkungen? Nur eine unnötige Logmeldung, oder konkrete Auswirkungen auf den Ladebetrieb?

**Comment by andig** [comment]
Gute Frage. Es ist ja nicht ganz klar, warum das passiert. Vertüddelt sich die FW und kommt bei mehrfachen Versuchen dann wieder klar? Man könnte das durchaus, z.b. mit kleinem exponential backoff falls sinnvoll, mehrfach probieren. Da in Summe recht viele Meßwerte abgerufen werden vllt. Bis zu 3s? Oder schickt das Ding immer von selbst alle seine Werte? Dann könnte man es natürlich auf Async umbauen. Könntest Du den Link zur Doku auch im Code ergänzen?

**Comment by andig** [comment]
Oder… es ist einfach ein Bug im RCT und sollte mittels FW-Update behoben werden? Ggf. Könnte dafür auch die Fehlermeldung den Mismatch konkret zeigen.

**Comment by TobiasHuber1980** [comment]
> Hi. Verstehe ich richtig, dass das ein RCT issue ist? Hat mich interessiert ob ich alleine bin mit dem Problem oder ob es auch andere haben...

@hrncvk hast du überhaupt eine Batterie an deiner PV-Anlage?

**Comment by TobiasHuber1980** [comment]
```
pv 1 power: invalid response: Cmd Response (05) Id #INVALID (4BC0F974) Data [69 215 80 0]
invalid response: Cmd Response (05) Id Battery power [W] (400F015B) Data [193 87 74 186]
grid energy: invalid response: Cmd Response (05) Id Battery power [W] (400F015B) Data [193 87 74 186]
pv 1 power: invalid response: Cmd Response (05) Id Battery power [W] (400F015B) Data [193 85 219 116]
```
wenn der Fehler auftritt, sieht man in evcc auch dass alle daten auf "0" sind, also keine PV-Produktion, kein Verbrauch etc....

**Comment by andig** [comment]
Ich hab nix was in einer Library verwendet würde. Das übliche Problem ist ja reconnect- dann müsste auch die Logik exposed werden. Wenn wirs einfach halten wollen akzeptieren wir den Fehler as-is oder bauen den internen (oder externen) retry?

**Comment by mlnoga** [comment]
Ja, ich mache interne Retries. Mit dem veränderten Zeitverhalten kommst Du dann klar, oder?

**Comment by andig** [comment]
Ähh, warte mal. Wenns den Retry eh braucht dann sollte ich den machen? Dann wär ein sentinel error aber schön um zu erkennen, dass der sich lohnt?

**Comment by hrncvk** [comment]
> > Hi. Verstehe ich richtig, dass das ein RCT issue ist? Hat mich interessiert ob ich alleine bin mit dem Problem oder ob es auch andere haben...
> 
> @hrncvk hast du überhaupt eine Batterie an deiner PV-Anlage?

ja habe ich 😅

**Comment by hrncvk** [comment]
> Erster Zwischenstand: evcc fragt den Ladezustand der Batterie ab (batterySoC, ID 0x959930BF). Vom RCT Laderegler kommt zwar ein Datenpaket mit gültiger Checksumme zurück. Doch es enthält einen ganz anderen Datenpunkt, nämlich die Spitzenleistung der Solarzellen. Hier der entsprechende Auszug aus der Herstellerdokumentation:
> 
> ```
> 0x4BC0F974, // 255: buf_v_control.power_reduction_max_solar | t_float |
> Solar plant peak power [Wp]
> ```
> 
> evcc fragt wieder den Ladezustand ab. Der RCT Laderegler gibt stattdessen folgenden Wert zurück:
> 
> ```
> 0xC0A7074F, // 681: net.slave_data | t_string |
> net.slave_data
> ```
> 
> Und das gleiche erneut bei Abfrage der Netzenergie (0xA59C8428).
> 
> Wie gehen wir robust damit um, wenn das Gerät nicht abgefragte Werte zurückliefert? Ein möglicher Weg könnte sein, die Abfrage einfach erneut zu versuchen. Dafür könnte man in https://github.com/mlnoga/rct/blob/main/connection.go#L108 einen Retry einbauen. Oder man ändert die bisher synchrone Architektur, und lagert das Auslesen von Antworten in einen nebenläufigen Thread aus. Das wäre ggf. robuster, aber auch deutlich aufwändiger.
> 
> Wie schwerwiegend sind denn die aktuellen Auswirkungen? Nur eine unnötige Logmeldung, oder konkrete Auswirkungen auf den Ladebetrieb?

Die App / Seite friert ein und wird träge aufjedenfall wenn ich zu lange drauf bleibe.

**Comment by hrncvk** [comment]
> also bei mir kommt der fehler immer noch.... wenn gefühlt auch weniger oft.
> 
> `pv 1 power: invalid response: Cmd Response (05) Id #INVALID (4BC0F974) Data [69 215 80 0]`
> 
> `battery 1 soc: invalid response: Cmd Response (05) Id #INVALID (C0A7074F) Data [71 240 52 38 80 83 32 56 46 48 32 68 83 76 69 0 0 0 0 0 0 0 0 0 0 0 0 0 171 32 97 69 183 252 110 193 0 0 0 63 0 0 5 13 0 0 0 0 50 46 51 46 53 54 54 49 0 0 0 0 0 0 0 0 48 48 54 53 66 52 56 50 51 50 52 54 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]`
> 
> @hrncvk bei dir auch?

Habe eben über das iPhone evcc aufgerufen und bekam nach 5 Sekunden das hier:

battery 1 soc: invalid response: Cmd Response (05) Id #INVALID (C0A7074F) Data [58 [189 129 108 80 83 32](tel:189 129 108 80 83 32) [49 48 46 48 32 86 87](tel:49 48 46 48 32 86 87) [52 81 0 0 0 0 0 0 0](tel:52 81 0 0 0 0 0 0 0) 0 0 0 0 [0 254 87 85 69 181 242](tel:0 254 87 85 69 181 242) [50 192 156 86 119](tel:50 192 156 86 119) [63 0 0 7 13 0 0 0 0](tel:63 0 0 7 13 0 0 0 0) [50 46 51 46 53 54 54](tel:50 46 51 46 53 54 54) [49 0 0 0 0 0 0 0 0 48](tel:49 0 0 0 0 0 0 0 0 48) [48 54 53 66 52 48 50](tel:48 54 53 66 52 48 50) [51 57 49 55 0 0 0 0](tel:51 57 49 55 0 0 0 0) 0 0 0 [0 223 21 0 0 0 0 0 0 0](tel:0 223 21 0 0 0 0 0 0 0) 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Gab es ein release wo das Update schon drin war oder hab ich was verpasst? Oder könnt ihr jungs das remote pushen?

**Comment by hrncvk** [comment]
Auch das bekam ich eben:

pv 1 power: invalid response: Cmd Response (05) Id #INVALID (4BC0F974) Data [70 60 232 0]

**Comment by andig** [comment]
Je nachdem was Du da probierst: nur weil das Problem in einer Library gelöst ist hat es noch keinen Weg in evcc gefunden.

**Comment by hrncvk** [comment]
> Je nachdem was Du da probierst: nur weil das Problem in einer Library gelöst ist hat es noch keinen Weg in evcc gefunden.

OK. Die Rückfrage kam daher, da das Issue geschlossen wurde ✌🏼

**Comment by TobiasHuber1980** [comment]
@mlnoga
nachdem (bei mir) immer noch diese "invalid response" Meldungen kommen, besteht eine Möglichkeit diese einfach zu unterdrücken?

**Comment by hrncvk** [comment]
> @mlnoga nachdem (bei mir) immer noch diese "invalid response" Meldungen kommen, besteht eine Möglichkeit diese einfach zu unterdrücken?

Bei mir besteht es ebenfalls ✌🏼

**Comment by AcidCells** [comment]
@mlnoga @andig Entschuldigt bitte, wenn ich mich an euch beide wende, bin noch ein bisschen neu hier und es tut mir leid, falls ich Regeln nicht befolgt habe. 

Ich habe bei mir einen RCT-POWER DC 10 Wechselrichter, eine passende Batterie dazu mit 11 KW (also 6 Einheiten) und 2 Strings, an denen die Zellen geclustert sind, also zu zwei Einheiten. Ich habe den Fehler mit der neuesten Firmware des Wechselrichters und der neuesten evcc Version immer noch. 

Es scheint ja wie @mlnoga  schreibt so zu sein, dass der Wechselrichter auf eine Frage eine andere/falsche Antwort gibt, die dann zu diesen Fehlern führt. Da diese fehlerhaften Antworten aber nur manchmal und dann auch nur teilweise für die Zellen oder die Batterie auftauchen, wäre eine echte Lösung, dass entweder:
- Der Fehler einfach ignoriert wird, und der bisher bekannte Wert bis zur nächsten reguläre Abfrage von evcc einfach beibehalten wird und erst mit einer gültigen Antwort überschrieben wird
- oder direkt ein Retry gemacht wird nur für den Wert, der die fehlerhafte Anfrage abwirft. (dies ggf. dann gekoppelt mit dem ersten Vorschlag, dass der zuletzt gültige Wert so lange beibehalten wird.)

Ich teste gerne ausgiebig, wenn gewünscht, habe evcc bisher auf Windows laufen, weil solange dieser Fehler existiert traue ich mich nicht, das in einen produktiven und Ehefrau-tauglichen Modus mit einem Raspberry und co. zu übernehmen :-)

Spenden mache ich auch gerne, falls das noch mehr motiviert !

Viele Grüße an euch
