### ISSUE TITLE
Invalid Response / Cmd Response - More stability needed

### ISSUE THREAD

**Issue by Baumus** [mlnoga/rct#13]
Quite often the response received by the rct power storage is flawed. As this behavior cannot be changed easily, I suggest to implement an effective error handling routine. I experimented with different approaches, the following (quickly translated by chatgpt `into` go) solved the issue and enabled stable performance:

```
// Query-Funktion mit robuster Fehlerbehandlung und Wiederholungslogik
func (c *Connection) Query(id Identifier) (*Datagram, error) {
	if dg, ok := c.cache.Get(id); ok {
		return dg, nil
	}

	const maxRetries = 10
	const startDelay = 100 * time.Millisecond
	const backoffMultiplier = 2
	var delay = startDelay

	for attempt := 0; attempt < maxRetries; attempt++ {
		c.builder.Build(&Datagram{Cmd: Read, Id: id, Data: nil})
		_, err := c.Send(c.builder)
		if err != nil {
			return nil, err
		}

		dg, err := c.Receive()
		if err != nil {
			if _, ok := err.(RecoverableError); ok {
				fmt.Printf("Recoverable error during parsing, attempt %d of %d: %v\n", attempt+1, maxRetries, err)
				time.Sleep(delay)
				delay *= time.Duration(backoffMultiplier)
				continue
			}
			return nil, err
		}

		if dg.Cmd == Response && dg.Id == id {
			c.cache.Put(dg)
			return dg, nil
		}

		err = RecoverableError{fmt.Sprintf("Mismatch of requested read of id: %v and response from source: %v", id, dg)}
		fmt.Println(err.Error())
		time.Sleep(delay)
		delay *= time.Duration(backoffMultiplier)
	}

	return nil, errors.New(fmt.Sprintf("Max retries reached for id: %v", id))
}
```

The idea behind the code:
By scheduling strategic delays between retries, the likelihood of subsequent requests being successful is increased, leading overall to a more resilient application.

What do you think about the suggestion? Can you implement such a routine or something else increasing reliability?

**Comment by AcidCells** [comment]
I would love to test this with my RCT hardware!

**Comment by Baumus** [comment]
@andig Es hat ein bisschen gedauert, aber ich habe verstanden, dass Du die Logik hier bereits implementiert hast: https://github.com/evcc-io/evcc/blob/3bf57f870ee66995c9a01784d93d9ac7e5ce7e02/meter/rct.go#L172 
@tobiashuber1980 Danke für den Hinweis.
